### PR TITLE
Fix #20

### LINKED ISSUE #20: Can't build only for darwin platform and x64 architecture.
I can't build any app for darwin x64. It trows me this error message:

    ✗ Sorry, building for darwin ia32 is not supported by Electron

However, I didn't check the `ia32` architecture checkbox when prompted.

[asciicast](https://asciinema.org/a/101186)

### PR DESCRIPTION
**Pull request by crushedice2000**
See the issue for more information.
This fixes a layer-8 bug done at programming time.

### CODE REVIEW

**Comment by zeke** [comment]
I ran into this bug today. cc @Urucas

**Comment by zeke** [comment]
cc @vrunoa and @pamepros, in case they're not watching notifications for the Urucas org. :)

**Comment by crushedice2000** [comment]
@vrunoa: Done! Tell me if I did what you asked me correctly.

**Comment by vrunoa** [comment]
v0.0.9 Published
[https://www.npmjs.com/package/electron-packager-interactive](https://www.npmjs.com/package/electron-packager-interactive)

**Comment by crushedice2000** [comment]
Thank you!

**Comment by zeke** [comment]
Nice. Looking forward to giving this project another try.

**Pull request merged**
