### PR TITLE
Enter now selects arch & platform

### LINKED ISSUE #6: It's possible to not select a platform or arch
If I hit enter to select a platform and then arch, I get the following:

```shell
epi
? Overwrite output directory ? Yes
? Use asar source packaging ? No
? Select Electron app source directory: /Users/adam/Code/GitHub/electron-quick-start
? Select Electron app output directory: /Users/adam/Code/GitHub/electron-quick-start/releases
? Select Application name: electron-quick-start
? Select App Bundle Id (optional): 
? Select App Version(optional): 0.0.1
? Select Electron icon file: 
? Select Electron version release: 0.34.1
? Select platforms: 
? Select architecture: 
Electron packager settings:
{ dir: '/Users/adam/Code/GitHub/electron-quick-start',
  name: 'electron-quick-start',
  platform: '',
  arch: '',
  version: '0.34.1',
  out: '/Users/adam/Code/GitHub/electron-quick-start/releases',
  'app-bundle-id': '',
  'app-version': '',
  overwrite: true,
  asar: false,
  icon: '',
  app_version: '0.0.1',
  bundle_id: '',
  appname: 'electron-quick-start',
  sourcedir: '/Users/adam/Code/GitHub/electron-quick-start',
  ignore: '/Users/adam/Code/GitHub/electron-quick-start/releases' }

✗ Error: Must specify arch
```

If I press space to check a selection then enter to move on to the next question, it works.

Latest version, on a Mac.

### PR DESCRIPTION
**Pull request by adam-lynch**
Fixes #6

### CODE REVIEW

**Comment by adam-lynch** [comment]
@vrunoa could you give this a test?

**Comment by vrunoa** [comment]
@adam-lynch if we change platform(arch) type to list, we can only select one platform(arch) at a time, and this is not the idea, since a user may want to create more than one release at a time. I would still consider to left the platform(arch) type to checkbox and set a default value in case the user press Enter without selecting any of them. What do you think ?

**Comment by adam-lynch** [comment]
@vrunoa I assumed that the user would just select `all` for the arch if they wanted both. Unless you meant they might want mac & windows, 64-bit (for example).

**Comment by vrunoa** [comment]
@adam-lynch exactly. Maybe some user just want to build for windows and mac avoiding linux, or any combination that just includes 2 platforms. 
Setting the input to a list type would remove this flow from the module. I believe the best solution for this case would be set the user platform(arch) as default. Also add a validation, throw an error when platform or arch os not selected. 
Let me know if you would like to implement this, otherwise I'll add this implementation.

**Comment by adam-lynch** [comment]
Ok. A default would be better than nothing but still would be pretty annoying if you thought you selected a certain arch and it defaulted to another. So maybe there needs to be a message something like "press space to select, enter to move to next step"?

**Comment by vrunoa** [comment]
@adam-lynch good idea. We can add this to the current message for platform(arch) selection.

**Pull request closed without merging**
